package blockchain

import "time"

//IsValidNewBlock : Checks if new block is valid regarding the latest block.
func IsValidNewBlock(newBlock *Block, latestBlock *Block, currentTimestamp time.Time) (bool, error) {
	if newBlock == nil || latestBlock == nil {
		return false, nil
	}

	// validate index
	expectedIndex := latestBlock.Index + 1
	if newBlock.Index != expectedIndex {
		return false, nil
	}

	// validate previous hash
	if newBlock.PreviousHash != latestBlock.Hash {
		return false, nil
	}

	// validate current hash
	expectedHash, err := newBlock.CalculateHash()
	if newBlock.Hash != expectedHash {
		return false, err
	}

	// validates if hash matches difficulty
	if !newBlock.HashMatchesDifficulty() {
		return false, nil
	}

	// validate timestamp
	if !newBlock.ValidateTimestamp(latestBlock, currentTimestamp) {
		return false, nil
	}

	// new block is valid
	return true, nil
}

//IsValidChain : Validates the whole block chain, including the first genesis block and all the rest.
func IsValidChain(blockchain []*Block, currentTimestamp time.Time) (bool, error) {
	if blockchain == nil || len(blockchain) == 0 {
		return false, nil
	}

	// lets validate genesis block first
	if !isGenesisBlockValid(blockchain[0]) {
		return false, nil
	}

	// loop through chain and validate all blocks with each other
	for index := 1; index < len(blockchain); index++ {

		isBlockValid, err := IsValidNewBlock(blockchain[index], blockchain[index-1], currentTimestamp)
		if !isBlockValid || err != nil {
			return false, err
		}
	}

	return true, nil
}

//isGenesisBlockValid : Validates genesis block by comparing it to block generated by GenesisBlock method.
func isGenesisBlockValid(block *Block) bool {
	// generate genesis block
	genesisBlock := GenesisBlock()

	// validate block values
	if block.Message != genesisBlock.Message {
		return false
	}

	if len(block.Transactions) != len(genesisBlock.Transactions) {
		return false
	}

	if block.Hash != genesisBlock.Hash {
		return false
	}

	if block.Index != genesisBlock.Index {
		return false
	}

	if block.PreviousHash != genesisBlock.PreviousHash {
		return false
	}

	if block.Timestamp != genesisBlock.Timestamp {
		return false
	}

	return true
}

//ValidateTimestamp : Checks if block timestamp is not too much in the future or in the past.
func (block *Block) ValidateTimestamp(latestBlock *Block, currentTimestamp time.Time) bool {

	// block should not be in the future more that 60s
	return block.Timestamp.Unix() <= currentTimestamp.Unix()+60 &&
		// block should not be more that 60s in the past from latest block
		block.Timestamp.Unix() >= latestBlock.Timestamp.Unix()-60
}
