package blockchain

import (
	"naivecoin/transactions"
	"time"
)

//IsValidNewBlock : Checks if new block is valid regarding the latest block.
func IsValidNewBlock(newBlock *Block, latestBlock *Block, currentTimestamp time.Time, unspentTransactionOutputs []*transactions.UnspentTransactionOutput) (bool, error) {
	if newBlock == nil || latestBlock == nil {
		return false, nil
	}

	// validate index
	expectedIndex := latestBlock.Index + 1
	if newBlock.Index != expectedIndex {
		return false, nil
	}

	// validate previous hash
	if newBlock.PreviousHash != latestBlock.Hash {
		return false, nil
	}

	// validate current hash
	expectedHash, err := newBlock.CalculateHash()
	if newBlock.Hash != expectedHash {
		return false, err
	}

	// validates if hash matches difficulty
	if !newBlock.HashMatchesDifficulty() {
		return false, nil
	}

	// validate timestamp
	if !newBlock.ValidateTimestamp(latestBlock, currentTimestamp) {
		return false, nil
	}

	// check if transactions are valid
	return transactions.ValidateBlockTransactions(newBlock.Transactions, unspentTransactionOutputs, newBlock.Index)
}

//isGenesisBlockValid : Validates genesis block by comparing it to block generated by GenesisBlock method.
func isGenesisBlockValid(block *Block) bool {
	// generate genesis block
	genesisBlock := GenesisBlock()

	// validate block values
	if block.Message != genesisBlock.Message {
		return false
	}

	if len(block.Transactions) != len(genesisBlock.Transactions) {
		return false
	}

	if block.Hash != genesisBlock.Hash {
		return false
	}

	if block.Index != genesisBlock.Index {
		return false
	}

	if block.PreviousHash != genesisBlock.PreviousHash {
		return false
	}

	if block.Timestamp != genesisBlock.Timestamp {
		return false
	}

	return true
}

//ValidateTimestamp : Checks if block timestamp is not too much in the future or in the past.
func (block *Block) ValidateTimestamp(latestBlock *Block, currentTimestamp time.Time) bool {

	// block should not be in the future more that 60s
	return block.Timestamp.Unix() <= currentTimestamp.Unix()+60 &&
		// block should not be more that 60s in the past from latest block
		block.Timestamp.Unix() >= latestBlock.Timestamp.Unix()-60
}
